### ISSUE TITLE
Need API support for copy function

### ISSUE THREAD

**Issue by SoujanyaPonnapalli** [RainBlock/merkle-patricia-tree#17]

**Comment by no2chem** [comment]
Okay, what should the copy function do? And should it take any parameters?

**Comment by SoujanyaPonnapalli** [comment]
So we just have an in-memory inplace merkle-patricia-tree. We are yet to make it copy-on-write. I see that we are not storing the tree in a hashMap with every node is a mapping hash(node) -> node. So this requires us to implement copy-on-write, right?
We need a copy-on-write copy function, which takes in no parameters and returns a copy of the merkle-patricia-tree.
